FROM nginx:stable-alpine

# Copy the built web app from the build stage
COPY /src/ /usr/share/nginx/html/

RUN mkdir -p /usr/share/nginx/html/leaderboard/

COPY /src/ /usr/share/nginx/html/leaderboard/

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 81