---
image: $DOCKER_IMAGE
variables:
  IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://10.3.1.3:2376/

stages:
  - build
  - push
  - deploy
  - security

services:
  - name: $RUNNER_IMAGE
    alias: docker

Build image:
  stage: build
  before_script: &before_script
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE:$CI_COMMIT_SHORT_SHA -t $IMAGE:$CI_COMMIT_SHORT_SHA api/
    - docker push $IMAGE:$CI_COMMIT_SHORT_SHA
  only:
    - prod
    - main

Push image:
  stage: push
  before_script: *before_script
  script:
    - docker pull $IMAGE:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE:$CI_COMMIT_SHORT_SHA $IMAGE:latest
    - docker push $IMAGE:latest
  only:
    - prod
