---
version: "3.8"
services:
  db:
    container_name: db_inte
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - ./application_data/db:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - 3306:3306

  api:
    container_name: api_inte
    image: api_inte:latest
    restart: unless-stopped
    env_file:
      - api.env
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_started

  app:
    container_name: app_inte
    image: app_inte:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./rproxy.conf:/etc/nginx/conf.d/nginx.conf
    environment:
      - TZ=Europe/Paris
    depends_on:
      api:
        condition: service_started
