---
version: "3.8"
services:
  db:
    container_name: db_inte
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - ./application_data/db:/var/lib/mysql
    env_file:
      - db.env
    networks:
      - nginx_int_net

  api:
    container_name: api_inte
    image: api_inte:latest
    restart: unless-stopped
    env_file:
      - api.env
    depends_on:
      db:
        condition: service_started
    networks:
      - nginx_int_net

  app:
    container_name: app_inte
    image: app_inte:latest
    restart: unless-stopped
    volumes:
      - ./rproxy.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      api:
        condition: service_started
    networks:
      - nginx_int_net

  leaderboard:
    container_name: leaderboard
    image: leaderboard:latest
    restart: unless-stopped
    env_file:
      - leaderboard.env
    depends_on:
      db:
        condition: service_started
    networks:
      - nginx_int_net

networks:
  nginx_int_net:
    external: true
