---
version: "3.8"
services:
  app:
    container_name: app_inte
    image: app_inte:latest
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./rproxy.conf:/etc/nginx/conf.d/nginx.conf
    environment:
      - TZ=Europe/Paris

  api:
    container_name: api_inte
    image: api_inte:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - TZ=Europe/Paris
